### ISSUE TITLE
Just what I'm looking for ... but....

### ISSUE THREAD

**Issue by gap777** [nodenv/jetbrains-npm#3]
First off, THANK YOU. We use nodenv for all our app dev, and I'm a little surprised that RubyMine doesn't support it better out of the box. Thanks for investigating the issue and bring a fix to the table.

I use the standard ~/.nodenv location, and have configured RM (see attached screenshot).

When I go to download libraries, I get this error dialog. Does it work for you? Any suggestions?

Thanks
<img width="994" alt="Screen Shot 2020-02-04 at 2 55 15 PM" src="https://user-images.githubusercontent.com/6495610/73781556-71cd4f80-475e-11ea-93d5-dbd4eaa670bc.png">

<img width="439" alt="Screen Shot 2020-02-04 at 2 56 04 PM" src="https://user-images.githubusercontent.com/6495610/73781865-02a42b00-475f-11ea-9a9a-5a1afd46354f.png">

**Comment by jasonkarns** [comment]
Are you confident that you can install modules with that node _outside_ of jetbrains? It looks like that node version itself needs recompiled (missing libs).

**Comment by gap777** [comment]
I use nodenv, and use node just fine. The  prob really is that Jetbrains doesn’t really support nodenv properly.

**Comment by jasonkarns** [comment]
This error message, however, indicates that the selected node version is missing necessary libraries, which seems unrelated to the rubymine hack (or even nodenv itself). This is a common problem after an OS upgrade. (related https://stackoverflow.com/questions/53828891/dyld-library-not-loaded-usr-local-opt-icu4c-lib-libicui18n-62-dylib-error-run)

Can you share the output if you run the same npm install command from the project directory via terminal instead of rubymine?
